### ISSUE TITLE
error when loading local data

### ISSUE THREAD

**Issue by gdiazcruz** [sdrogers/nplinker#129]
Hello!
I'm running NPLinker on Linux but using the Docker workflow. At some point, I get the following error, and I am not sure what's causing it. I thought it was that the antismash format, so I changed it to flat from default, but it didn't work. Is there anything else I should be doing? Thanks in advance!!

22:39:50 [INFO] genomics.py:266, Using antiSMASH filename delimiters ['.', '_', '-']
2023-03-16 22:39:50,976 Error in server loaded hook ValueError('substring not found')
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/bokeh/server/contexts.py", line 193, in run_load_hook
    self._application.on_server_loaded(self.server_context)
  File "/usr/local/lib/python3.10/site-packages/bokeh/application/application.py", line 209, in on_server_loaded
    h.on_server_loaded(server_context)
  File "/usr/local/lib/python3.10/site-packages/bokeh/application/handlers/directory.py", line 262, in on_server_loaded
    return self._lifecycle_handler.on_server_loaded(server_context)
  File "/usr/local/lib/python3.10/site-packages/bokeh/application/handlers/lifecycle.py", line 92, in on_server_loaded
    return self._on_server_loaded(server_context)
  File "/app/nplinker/server_lifecycle.py", line 62, in on_server_loaded
    nh.load()
  File "/app/nplinker/server_lifecycle.py", line 20, in load
    self.load_nplinker()
  File "/app/nplinker/server_lifecycle.py", line 43, in load_nplinker
    if not self.nplinker.load_data():
  File "/usr/local/lib/python3.10/site-packages/nplinker/nplinker.py", line 272, in load_data
    if not self._loader.load(met_only=met_only):
  File "/usr/local/lib/python3.10/site-packages/nplinker/loader.py", line 337, in load
    if not met_only and not self._load_genomics():
  File "/usr/local/lib/python3.10/site-packages/nplinker/loader.py", line 691, in _load_genomics
    self.gcfs, self.bgcs, self.strains, unknown_strains = loadBGC_from_cluster_files(
  File "/usr/local/lib/python3.10/site-packages/nplinker/genomics.py", line 283, in loadBGC_from_cluster_files
    nname = name[:name.index('.')]
ValueError: substring not found

**Comment by gdiazcruz** [comment]
Follow up:
I tried running Big-Scape instead of using files from a separate run, and this is what I got:

	Main function took 11796.905 s
02:01:07 [INFO] runbigscape.py:63, BiG-SCAPE completed with return code 0
02:01:07 [INFO] loader.py:95, Trying to discover correct bigscape directory under /data/metabolomics/bigscape
02:01:07 [INFO] loader.py:99, Found network files directory: /data/metabolomics/bigscape/network_files/2023-03-16_22-44-29_hybrids_glocal
02:01:07 [INFO] genomics.py:538, Found 1816 MiBIG json files
02:01:08 [WARNING] loader.py:646, 1 missing annotation tsv files:
02:01:08 [WARNING] loader.py:648,   1/1: /data/metabolomics/bigscape/network_files/2023-03-16_22-44-29_hybrids_glocal/Saccharides/Network_Annotations_Saccharides.tsv
02:01:08 [WARNING] loader.py:646, 1 missing clustering tsv files:
02:01:08 [WARNING] loader.py:648,   1/1: /data/metabolomics/bigscape/network_files/2023-03-16_22-44-29_hybrids_glocal/Saccharides/Saccharides_clustering_c0.30.tsv
02:01:08 [WARNING] loader.py:646, 1 missing network files:
02:01:08 [WARNING] loader.py:648,   1/1: /data/metabolomics/bigscape/network_files/2023-03-16_22-44-29_hybrids_glocal/Saccharides/Saccharides_c0.30.network
02:01:08 [WARNING] loader.py:668, Product type Saccharides will be skipped due to missing files!
02:01:08 [INFO] genomics.py:266, Using antiSMASH filename delimiters ['.', '_', '-']
02:01:09 [INFO] downloader.py:89, Attempting to retrieve missing MiBIG BGC JSON data for BGC0001932
2023-03-17 02:01:10,922 Error in server loaded hook Exception('Unknown MiBIG BGC: original=BGC0001932.1 / parsed=BGC0001932')
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/bokeh/server/contexts.py", line 193, in run_load_hook
    self._application.on_server_loaded(self.server_context)
  File "/usr/local/lib/python3.10/site-packages/bokeh/application/application.py", line 209, in on_server_loaded
    h.on_server_loaded(server_context)
  File "/usr/local/lib/python3.10/site-packages/bokeh/application/handlers/directory.py", line 262, in on_server_loaded
    return self._lifecycle_handler.on_server_loaded(server_context)
  File "/usr/local/lib/python3.10/site-packages/bokeh/application/handlers/lifecycle.py", line 92, in on_server_loaded
    return self._on_server_loaded(server_context)
  File "/app/nplinker/server_lifecycle.py", line 62, in on_server_loaded
    nh.load()
  File "/app/nplinker/server_lifecycle.py", line 20, in load
    self.load_nplinker()
  File "/app/nplinker/server_lifecycle.py", line 43, in load_nplinker
    if not self.nplinker.load_data():
  File "/usr/local/lib/python3.10/site-packages/nplinker/nplinker.py", line 272, in load_data
    if not self._loader.load(met_only=met_only):
  File "/usr/local/lib/python3.10/site-packages/nplinker/loader.py", line 337, in load
    if not met_only and not self._load_genomics():
  File "/usr/local/lib/python3.10/site-packages/nplinker/loader.py", line 691, in _load_genomics
    self.gcfs, self.bgcs, self.strains, unknown_strains = loadBGC_from_cluster_files(
  File "/usr/local/lib/python3.10/site-packages/nplinker/genomics.py", line 295, in loadBGC_from_cluster_files
    raise Exception(
Exception: Unknown MiBIG BGC: original=BGC0001932.1 / parsed=BGC0001932

**Comment by MenusGarg** [comment]
Hi Gustavo

Exception: Unknown MiBIG BGC: original=BGC0001932.1 / parsed=BGC0001932
This exception is occurring because this has a modified version with new BGC id on mibig database and the antismash file you are using is not updated. I would suggest you to run antismash again and start over!!

Hope it helps
Thanks 
Menus Garg

**Comment by gdiazcruz** [comment]
Thanks Menus, that suggestion solved the problem!
