### ISSUE TITLE
WebApp shows no data in tables

### ISSUE THREAD

**Issue by louwenjjr** [sdrogers/nplinker#63]
Hi Andrew,

I was trying my Crusemann data with the webapp v1.1.3 and it shows empty tables, while it does show the correct number of objects in the data in the upper right corner:
![image](https://user-images.githubusercontent.com/62542407/157678965-922ebfaf-9692-461d-b278-577d7eea9c89.png)

When the webapp initialised I got this error:
```
2022-03-10 14:01:01,445 WebSocket connection opened
2022-03-10 14:01:01,447 Uncaught exception GET /npapp/ws (172.17.42.1)
HTTPServerRequest(protocol='http', host='localhost:5006', method='GET', uri='/npapp/ws', version='HTTP/1.1', remote_ip='172.17.42.1')
Traceback (most recent call last):
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/tornado/websocket.py", line 954, in _accept_connection
    open_result = handler.open(*handler.open_args, **handler.open_kwargs)
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/tornado/web.py", line 3173, in wrapper
    return method(self, *args, **kwargs)
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/server/views/ws.py", line 140, in open
    raise ProtocolError("Token is expired.")
bokeh.protocol.exceptions.ProtocolError: Token is expired.
```

When I refresh the page the tables are still not populated and when I try to change some settings for metcalf scoring I get this (I guess because there are no objects to link?):
```
on_session_created
14:01:34 [INFO] methods.py:436, MetcalfScoring.setup (bgcs=5869, gcfs=1581, spectra=13667, molfams=8346, strains=154)
14:01:34 [INFO] methods.py:465, MetcalfScoring.setup preprocessing dataset (this may take some time)
14:04:01 [INFO] methods.py:476, MetcalfScoring.setup completed
*** DB user_version is currently 3, expecting 3
layout done, adding widget roots
bokeh_layout method complete
2022-03-10 14:04:01,966 WebSocket connection opened
2022-03-10 14:04:01,967 ServerConnection created
2022-03-10 14:04:15,189 error handling message
 message: Message 'PATCH-DOC' content: {'events': [{'kind': 'ModelChanged', 'model': {'id': '1009'}, 'attr': 'value', 'new': 2}], 'references': []}
```

When I use one of the PoDP datasets, everything works okay and data gets loaded with metcalf scoring, until I try to change one of the scoring settings and it crashes with a similar message:

```
2022-03-15 09:15:38,652 error handling message
 message: Message 'PATCH-DOC' content: {'events': [{'kind': 'ModelChanged', 'model': {'id': '1010'}, 'attr': 'value', 'new': 0.1}], 'references': []}
 error: AttributeError("'NPLinkerBokeh' object has no attribute 'get_links'",)
Traceback (most recent call last):
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/server/protocol_handler.py", line 90, in handle
    work = await handler(message, connection)
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/server/session.py", line 67, in _needs_document_lock_wrapper
    result = func(self, *args, **kwargs)
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/server/session.py", line 261, in _handle_patch
    message.apply_to_document(self.document, self)
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/protocol/messages/patch_doc.py", line 100, in apply_to_document
    doc._with_self_as_curdoc(lambda: doc.apply_json_patch(self.content, setter))
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/document/document.py", line 1198, in _with_self_as_curdoc
    return f()
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/protocol/messages/patch_doc.py", line 100, in <lambda>
    doc._with_self_as_curdoc(lambda: doc.apply_json_patch(self.content, setter))
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/document/document.py", line 411, in apply_json_patch
    patched_obj.set_from_json(attr, value, models=references, setter=setter)
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/core/has_props.py", line 412, in set_from_json
    descriptor.set_from_json(self, json, models, setter)
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/core/property/descriptors.py", line 623, in set_from_json
    return super().set_from_json(obj, self.property.from_json(json, models), models, setter)
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/core/property/descriptors.py", line 327, in set_from_json
    self._internal_set(obj, json, setter=setter)
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/core/property/descriptors.py", line 786, in _internal_set
    self._real_set(obj, old, value, hint=hint, setter=setter)
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/core/property/descriptors.py", line 849, in _real_set
    self._trigger(obj, old, value, hint=hint, setter=setter)
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/core/property/descriptors.py", line 926, in _trigger
    obj.trigger(self.name, old, value, hint, setter)
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/model.py", line 682, in trigger
    super().trigger(descriptor.name, old, new, hint=hint, setter=setter)
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/util/callback_manager.py", line 163, in trigger
    self._document._notify_change(self, attr, old, new, hint, setter, invoke)
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/document/document.py", line 1090, in _notify_change
    self._trigger_on_change(event)
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/document/document.py", line 1180, in _trigger_on_change
    self._with_self_as_curdoc(event.callback_invoker)
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/document/document.py", line 1198, in _with_self_as_curdoc
    return f()
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/util/callback_manager.py", line 161, in invoke
    callback(attr, old, new)
  File "/app/nplinker/webapp/npapp/main.py", line 467, in rosetta_spec_cutoff_callback
    self.get_links()
AttributeError: 'NPLinkerBokeh' object has no attribute 'get_links'
```

Cheers,
Joris

**Comment by andrewramsay** [comment]
> bokeh.protocol.exceptions.ProtocolError: Token is expired.

This seems to indicate there's some timeout occurring in the WebSocket code that bokeh uses to communicate between its Python and Javascript parts. Did that dataset take an unusually long time to load or anything along those lines? Does it happen every time? I think there's a way to increase the session timeout but might be better if we can find why it is taking long enough to expire, I haven't seen that happen before.

> AttributeError: 'NPLinkerBokeh' object has no attribute 'get_links'

I think the call to get_links should have been removed previously, it's a reference to some of the code that used to be there to handle the plots UI... not sure how I haven't noticed that sooner! I'll try to get that fixed and push out a 1.1.4 Docker version later today.

**Comment by louwenjjr** [comment]
Thanks for your quick reply, Andrew :)

>This seems to indicate there's some timeout occurring in the WebSocket code that bokeh uses to communicate between its Python and Javascript parts. Did that dataset take an unusually long time to load or anything along those lines? Does it happen every time? I think there's a way to increase the session timeout but might be better if we can find why it is taking long enough to expire, I haven't seen that happen before.


Yes, it happens every time. I don't think it takes unusually long.. It seems to load quickly after the nplinker code has finished. Could it be because it is a rather large dataset (150 strains, 500 metabolome files)? If it helps this is what it prints at the start:
```
docker run --name webapp --user $(id -u):$(id -g) -p 5006:5006 -v /mnt/scratch/louwe015/NPLinker/own/nplinker_shared:/data:rw andrewramsay/nplinker:latest
Warning: plotting functionality will not be available (missing matplotlib and/or seaborn)
2022-03-15 15:01:09,727 Watching: /app/nplinker/webapp/npapp/theme.yaml
2022-03-15 15:01:09,728 Watching: /app/nplinker/webapp/npapp/static/css/ChemDoodleWeb.css
2022-03-15 15:01:09,728 Watching: /app/nplinker/webapp/npapp/static/css/npapp.css
2022-03-15 15:01:09,728 Watching: /app/nplinker/webapp/npapp/static/css/bootstrap.min.css
2022-03-15 15:01:09,728 Watching: /app/nplinker/webapp/npapp/templates/tmpl.onclick.py.html
2022-03-15 15:01:09,728 Watching: /app/nplinker/webapp/npapp/templates/tmpl.basic.py.html
2022-03-15 15:01:09,728 Watching: /app/nplinker/webapp/npapp/templates/index.html
2022-03-15 15:01:09,728 Watching: /app/nplinker/webapp/npapp/templates/tmpl.basic.search.py.html
2022-03-15 15:01:09,728 Watching: /app/nplinker/webapp/npapp/templates/tmpl.onclick.search.py.html
2022-03-15 15:01:09,728 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2022-03-15 15:01:09,730 User authentication hooks NOT provided (default user enabled)
2022-03-15 15:01:09,735 Bokeh app running at: http://localhost:5006/npapp
2022-03-15 15:01:09,735 Starting Bokeh server with process id: 1
on_server_loaded
DATAPATH: /data/nplinker.toml
```

> I think the call to get_links should have been removed previously, it's a reference to some of the code that used to be there to handle the plots UI... not sure how I haven't noticed that sooner! I'll try to get that fixed and push out a 1.1.4 Docker version later today.

Okay great! Then I don't have to worry about that.

**Comment by louwenjjr** [comment]
Okay I deleted some things, and I think it might have gotten stuck because the sqlite database was empty.. It now created a new sqlite file v3 and it works again. Now I'm running into another problem when I try to do rosetta scoring:

```
NAMES ['metcalf', 'rosetta']
2022-03-15 15:14:15,339 error handling message
 message: Message 'PATCH-DOC' content: {'events': [{'kind': 'MessageSent', 'msg_type': 'bokeh_event', 'msg_data': {'event_name': 'button_click', 'event_values': {}}}], 'references': []}
 error: AttributeError("'BGC' object has no attribute 'parent'",)
Traceback (most recent call last):
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/server/protocol_handler.py", line 90, in handle
    work = await handler(message, connection)
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/server/session.py", line 67, in _needs_document_lock_wrapper
    result = func(self, *args, **kwargs)
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/server/session.py", line 261, in _handle_patch
    message.apply_to_document(self.document, self)
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/protocol/messages/patch_doc.py", line 100, in apply_to_document
    doc._with_self_as_curdoc(lambda: doc.apply_json_patch(self.content, setter))
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/document/document.py", line 1198, in _with_self_as_curdoc
    return f()
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/protocol/messages/patch_doc.py", line 100, in <lambda>
    doc._with_self_as_curdoc(lambda: doc.apply_json_patch(self.content, setter))
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/document/document.py", line 398, in apply_json_patch
    self._trigger_on_message(event_json["msg_type"], event_json["msg_data"])
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/document/document.py", line 687, in _trigger_on_message
    cb(msg_data)
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/document/document.py", line 356, in apply_json_event
    model._trigger_event(event)
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/util/callback_manager.py", line 91, in _trigger_event
    self._document._with_self_as_curdoc(invoke)
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/document/document.py", line 1198, in _with_self_as_curdoc
    return f()
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/util/callback_manager.py", line 78, in invoke
    callback()
  File "/app/nplinker/webapp/npapp/main.py", line 882, in tables_score_met_callback
    results = self.nh.nplinker.get_links(selected_spectra, current_methods, and_mode=self.score_helper.method_and_mode)
  File "/app/nplinker/webapp/npapp/../../prototype/nplinker/nplinker.py", line 379, in get_links
    link_collection = method.get_links(objects_for_method, link_collection)
  File "/app/nplinker/webapp/npapp/../../prototype/nplinker/scoring/methods.py", line 392, in get_links
    target = hit.bgc if not self.bgc_to_gcf else hit.bgc.parent
AttributeError: 'BGC' object has no attribute 'parent'
```

I think it happens here: https://github.com/sdrogers/nplinker/blob/a13337cf4d1d4a8cc6fe9079d559205fc4f854b0/prototype/nplinker/scoring/methods.py#L392

Maybe because of the hybrid bgc solution, bgcs now have parents instead of parent?

**Comment by andrewramsay** [comment]
Looks like it - this is exactly the kind of thing that having some more tests would have easily caught, I just haven't had time to set any up unfortunately. 

The bgc_to_gcf thing was originally a workaround for parsing scoring results at one point in the webapp where the assumption was the objects returned would be GCFs. The original Rosetta code returns BGCs so having bgc_to_gcf=True would swap each one for its parent GCF and keep it consistent with how Metcalf works. 

If there's only one parent GCF then things are simple, but what happens if it's a hybrid BGC? Do we simply iterate through the set of parents and create an entry in the results for every GCF? Easy enough to do, just not sure if that makes sense or not?

**Comment by justinjjvanderhooft** [comment]
I think your proposed solution would work @andrewramsay - I don't think there is a "right" or "wrong" solution here - the alternative would be to ignore the hybrid BGCs.... what do you think @louwenjjr ?

**Comment by louwenjjr** [comment]
>Looks like it - this is exactly the kind of thing that having some more tests would have easily caught, I just haven't had time to set any up unfortunately.

Totally agree, I think the eScience people might have time for this which would be very nice.

>If there's only one parent GCF then things are simple, but what happens if it's a hybrid BGC? Do we simply iterate through the set of parents and create an entry in the results for every GCF? Easy enough to do, just not sure if that makes sense or not?

Very good point.. I think I would create an entry in the results for every parent GCF indeed.. The way rosetta works is already a tiny bit ambiguous as it maps a rosetta hit already from one child BGC to the parent GCF right? So mapping a rosetta hit to all the parent GCFs would make sense to me.

**Comment by andrewramsay** [comment]
OK, I'll include this and the get_links fix in a v1.1.4 release later today.

**Comment by justinjjvanderhooft** [comment]
👍 😊

**Comment by andrewramsay** [comment]
Changes to the Rosetta code are in 61908e2871d4d67ac3159f937aa84d2202aebedf 

I ended up uncovering and fixing a few different bugs while I was poking around as a result of this though so instead of me pushing another release immediately, I've built a new test image you can pull from `andrewramsay/nplinker:testing`. If you can try this out with a couple of datasets that'd be good! Assuming that doesn't expose any further problems then I can do a proper release afterwards.

**Comment by louwenjjr** [comment]
Sounds good!

**Comment by louwenjjr** [comment]
The webapp seems to work now again for my data!

I just have a small issue that GCFs do not link anymore to BGCs, i.e. if I select a GCF there is no selection made on the BGCs. The other way around does work: if I make a selection on BGCs, GCFs are selected.

For a PoDP entry I get this error:
```
docker run --name webapp --user $(id -u):$(id -g) -p 5006:5006 -v /mnt/scratch/louwe015/NPLinker/own/nplinker_shared:/data:rw andrewramsay/nplinker:testing
Warning: plotting functionality will not be available (missing matplotlib and/or seaborn)
2022-03-17 09:01:59,161 Watching: /app/webapp/npapp/theme.yaml
2022-03-17 09:01:59,162 Watching: /app/webapp/npapp/static/css/ChemDoodleWeb.css
2022-03-17 09:01:59,162 Watching: /app/webapp/npapp/static/css/npapp.css
2022-03-17 09:01:59,162 Watching: /app/webapp/npapp/static/css/bootstrap.min.css
2022-03-17 09:01:59,162 Watching: /app/webapp/npapp/templates/tmpl.onclick.py.html
2022-03-17 09:01:59,162 Watching: /app/webapp/npapp/templates/tmpl.basic.py.html
2022-03-17 09:01:59,162 Watching: /app/webapp/npapp/templates/index.html
2022-03-17 09:01:59,162 Watching: /app/webapp/npapp/templates/tmpl.basic.search.py.html
2022-03-17 09:01:59,162 Watching: /app/webapp/npapp/templates/tmpl.onclick.search.py.html
2022-03-17 09:01:59,162 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2022-03-17 09:01:59,164 User authentication hooks NOT provided (default user enabled)
2022-03-17 09:01:59,169 Bokeh app running at: http://localhost:5006/npapp
2022-03-17 09:01:59,169 Starting Bokeh server with process id: 1
on_server_loaded
DATAPATH: /data/nplinker.toml
09:01:59 [DEBUG] config.py:86, Parsing default config file: /data/.config/nplinker/nplinker.toml
09:01:59 [DEBUG] config.py:89, Loading user config /data/nplinker.toml
09:01:59 [INFO] config.py:117, Selected platform project ID MSV000078839
09:01:59 [INFO] downloader.py:159, Downloader for MSV000078839, caching to /data/nplinker_data/pairedomics
09:01:59 [INFO] downloader.py:162, Downloading new copy of platform project data...
2022-03-17 09:01:59,216 Error in server loaded hook Exception('Failed to download http://pairedomicsdata.bioinformatics.nl/api/projects (status code 301)',)
Traceback (most recent call last):
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/server/contexts.py", line 173, in run_load_hook
    self._application.on_server_loaded(self.server_context)
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/application/application.py", line 186, in on_server_loaded
    h.on_server_loaded(server_context)
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/application/handlers/directory.py", line 232, in on_server_loaded
    return self._lifecycle_handler.on_server_loaded(server_context)
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/application/handlers/lifecycle.py", line 75, in on_server_loaded
    return self._on_server_loaded(server_context)
  File "/app/webapp/npapp/server_lifecycle.py", line 58, in on_server_loaded
    nh.load()
  File "/app/webapp/npapp/server_lifecycle.py", line 22, in load
    self.load_nplinker()
  File "/app/webapp/npapp/server_lifecycle.py", line 40, in load_nplinker
    self.nplinker = NPLinker(datapath)
  File "/app/webapp/npapp/../../prototype/nplinker/nplinker.py", line 116, in __init__
    self._loader = DatasetLoader(self._config.config)
  File "/app/webapp/npapp/../../prototype/nplinker/loader.py", line 143, in __init__
    self._downloader = Downloader(self._platform_id)
  File "/app/webapp/npapp/../../prototype/nplinker/pairedomics/downloader.py", line 163, in __init__
    self.all_project_json = self._download_platform_json_to_file(PAIREDOMICS_PROJECT_DATA_ENDPOINT, self.all_project_json_file)
  File "/app/webapp/npapp/../../prototype/nplinker/pairedomics/downloader.py", line 681, in _download_platform_json_to_file
    raise Exception('Failed to download {} (status code {})'.format(url, resp.status_code))
Exception: Failed to download http://pairedomicsdata.bioinformatics.nl/api/projects (status code 301)
```

I checked and https://pairedomicsdata.bioinformatics.nl/api/projects seems to be live and MSV000078839 is in there. Any idea what happens here?

**Comment by andrewramsay** [comment]
> I just have a small issue in the webapp that GCFs do not link anymore to BGCs, i.e. if I select a GCF there is no selection made on the BGCs. The other way around does work: if I make a selection on BGCs, GCFs are selected.

OK, I'll look into that later today.

> I checked and https://pairedomicsdata.bioinformatics.nl/api/projects seems to be live and MSV000078839 is in there. Any idea what happens here?

My guess would be the HTTP library is treating the 301 response code ("Moved Permanently") as an error instead of actually following the redirect it's been given - NPLinker is still using an `http://` link to the API but I see it's been shifted to `https://` at some point so that'll be why it's generating the 301 redirect. I'll update the URL in downloader.py to use HTTPS and that should fix it.

**Comment by louwenjjr** [comment]
>My guess would be the HTTP library is treating the 301 response code ("Moved Permanently") as an error instead of actually following the redirect it's been given - NPLinker is still using an http:// link to the API but I see it's been shifted to https:// at some point so that'll be why it's generating the 301 redirect. I'll update the URL in downloader.py to use HTTPS and that should fix it.

Ah right I see it now. Thank you!

>One possible reason for that not working is if the SQLite database that stores the links has only been partially constructed due to one of the previous bugs. Can you try removing your .../nplinker_data/tables_links/dataset/ folder and run the webapp again and see if that helps?

Right, that worked! Now I just notice it is a bit slow, but that is fine. I need to remember that I need to remove all the output NPLinker files when I encounter a bug...
```
table gcf_table, selected = [3]
table_callback: query
createTempTable (totSel=1) took 24.28s
table_callback: updating data sources
table_callback gcf_table done
table gcf_table, selected = [13]
table_callback: query
createTempTable (totSel=1) took 5.09s
table_callback: updating data sources
table_callback gcf_table done
```

**Comment by andrewramsay** [comment]
> I need to remember that I need to remove all the output NPLinker files when I encounter a bug...

I think I can also improve the way it checks if the database is actually valid to avoid this having to be done manually. It should avoid this kind of problem if it checks that the number of objects in the various database tables matches what has been loaded from the dataset. If there's any mismatch it can assume something has changed and rebuild the database.

**Comment by louwenjjr** [comment]
>I think I can also improve the way it checks if the database is actually valid to avoid this having to be done manually. It should avoid this kind of problem if it checks that the number of objects in the various database tables matches what has been loaded from the dataset. If there's any mismatch it can assume something has changed and rebuild the database.

Yea I think that would be a great addition!
